const express=require("express");
const cors=require("cors");
const helmet=require("helmet");
const rateLimit=require("express-rate-limit");
const cookieParser=require("cookie-parser");
const authMiddleware=require("./midleware/authMiddleware");
const adminLoginRouter=require("./routes/adminLoginRouter");
const partiesRouter=require("./routes/partiesRouter");
const entryRouter=require("./routes/entryRouter");
const expenseRouter=require("./routes/expenseRouter");
const Sale=require("./models/SaleModel");
const Purchase=require("./models/purchaseModel");
const Service=require("./models/serviceModel");
const Expense=require("./models/expenseModel");
const Transaction=require("./models/transactionModel");
const Party=require("./models/partModel");
const app=express();
const origins=(process.env.FRONTEND_URL||"http://localhost:5173").split(",").map(x=>x.trim());
app.set("trust proxy",1);app.use(helmet());app.use(cors({origin:(origin,cb)=>!origin||origins.includes(origin)?cb(null,true):cb(new Error("CORS blocked")),credentials:true}));app.use(express.json({limit:"1mb"}));app.use(cookieParser());
app.use("/api",rateLimit({windowMs:15*60*1000,max:200,standardHeaders:true,legacyHeaders:false}));
app.use("/api/admin",adminLoginRouter);
app.use("/api/admin",authMiddleware,partiesRouter);
app.use("/api",authMiddleware,entryRouter,expenseRouter);
app.get("/api/dashboard",authMiddleware,async(_req,res)=>{try{const [sale,purchase,service,expense,parties,paid,pending,recent]=await Promise.all([Sale.aggregate([{$group:{_id:null,total:{$sum:"$amount"},count:{$sum:1}}}]),Purchase.aggregate([{$group:{_id:null,total:{$sum:"$amount"},count:{$sum:1}}}]),Service.aggregate([{$group:{_id:null,total:{$sum:"$amount"},count:{$sum:1}}}]),Expense.aggregate([{$group:{_id:null,total:{$sum:"$amount"},count:{$sum:1}}}]),Party.countDocuments({isActive:true}),Transaction.aggregate([{$match:{paymentStatus:"paid"}},{$group:{_id:null,total:{$sum:"$amount"}}}]),Transaction.aggregate([{$match:{paymentStatus:"pending"}},{$group:{_id:null,total:{$sum:"$amount"}}}]),Transaction.find().populate("partyId","name").sort({createdAt:-1}).limit(6).lean()]);return res.json({success:true,stats:{sale:sale[0]?.total||0,purchase:purchase[0]?.total||0,service:service[0]?.total||0,expense:expense[0]?.total||0,partyCount:parties,paid:paid[0]?.total||0,pending:pending[0]?.total||0},recent:recent.map(x=>({id:x._id,type:x.type,partyName:x.partyId?.name||"Unknown",amount:x.amount,status:x.paymentStatus,date:x.createdAt}))});}catch(e){console.error(e);res.status(500).json({success:false,message:"Unable to load dashboard"});}});
app.get("/api/health",(_req,res)=>res.json({success:true,status:"ok",timestamp:new Date()}));
app.get("/",(_req,res)=>res.json({success:true,message:"Fusion API is running"}));
app.use((err,_req,res,_next)=>{console.error(err);res.status(500).json({success:false,message:"Unexpected server error"})});
module.exports=app;
